// Emoji mã hóa đến Unicode mapping

export const EMOJI_MAP: Record<string, string> = {
  ':smile:': '😀',
  ':joy:': '😂',
  ':heart_eyes:': '😍',
  ':thinking:': '🤔',
  ':cry:': '😢',
  ':sunglasses:': '😎',
  ':blush:': '😊',
  ':grin:': '😁',
  ':laughing:': '😆',
  ':sweat_smile:': '😅',
  ':sweat:': '😓',
  ':sob:': '😭',
  ':angry:': '😤',
  ':rage:': '😡',
  ':hugging:': '🤗',
  ':kissing_heart:': '😘',
  ':wink:': '😉',
  ':stuck_out_tongue:': '😛',
  ':neutral:': '😐',
  ':expressionless:': '😑',
  ':thumbsup:': '👍',
  ':thumbsdown:': '👎',
  ':wave:': '👋',
  ':clap:': '👏',
  ':pray:': '🙏',
  ':v:': '✌️',
  ':handshake:': '🤝',
  ':fist:': '👊',
  ':fist_raised:': '✊',
  ':hand:': '🖐️',
  ':ok_hand:': '👌',
  ':point_up:': '☝️',
  ':point_down:': '👇',
  ':point_left:': '👈',
  ':point_right:': '👉',
  ':heart:': '❤️',
  ':yellow_heart:': '💛',
  ':green_heart:': '💚',
  ':blue_heart:': '💙',
  ':purple_heart:': '💜',
  ':black_heart:': '🖤',
  ':broken_heart:': '💔',
  ':fire:': '🔥',
  ':star:': '⭐',
  ':sparkles:': '✨',
  ':100:': '💯',
  ':check:': '✅',
  ':x:': '❌',
  ':warning:': '⚠️',
  ':question:': '❓',
  ':tada:': '🎉',
  ':confetti:': '🎊',
  ':gift:': '🎁',
  ':balloon:': '🎈',
  ':cake:': '🎂',
  ':musical_note:': '🎵',
  ':soccer:': '⚽',
  ':basketball:': '🏀',
  ':video_game:': '🎮',
  ':trophy:': '🏆',
  ':medal:': '🏅',
  ':dog:': '🐶',
  ':cat:': '🐱',
  ':mouse:': '🐭',
  ':hamster:': '🐹',
  ':rabbit:': '🐰',
  ':fox:': '🦊',
  ':bear:': '🐻',
  ':panda:': '🐼',
  ':koala:': '🐨',
  ':tiger:': '🐯',
  ':lion:': '🦁',
  ':cow:': '🐮',
  ':pig:': '🐷',
  ':frog:': '🐸',
  ':monkey:': '🐵',
  ':pizza:': '🍕',
  ':hamburger:': '🍔',
  ':fries:': '🍟',
  ':popcorn:': '🍿',
  ':coffee:': '☕',
  ':beer:': '🍺',
  ':wine:': '🍷',
  ':ice_cream:': '🍦',
  ':doughnut:': '🍩',
  ':watermelon:': '🍉',
  ':apple:': '🍎',
  ':banana:': '🍌',
  ':sunny:': '☀️',
  ':cloud:': '☁️',
  ':rain:': '🌧️',
  ':snowflake:': '❄️',
  ':rainbow:': '🌈',
  ':moon:': '🌙',
  ':earth:': '🌍',
};

export function replaceEmojiShortcodes(text: string): string {
  let result = text;
  Object.entries(EMOJI_MAP).forEach(([code, emoji]) => {
    result = result.replaceAll(code, emoji);
  });
  return result;
}

// Lấy danh sách emoji và encode của nó
export const EMOJI_LIST = Object.entries(EMOJI_MAP).map(([code, emoji]) => ({
  code,
  emoji,
}));
